# Generated by Django 3.1.1 on 2021-03-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelter_id', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('intake_date', models.DateTimeField(auto_now_add=True)),
                ('species', models.CharField(blank=True, default=None, max_length=255)),
                ('breed', models.CharField(blank=True, default=None, max_length=255)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], default=None, max_length=255)),
                ('age_years', models.IntegerField(blank=True, default=None)),
                ('age_months', models.IntegerField(blank=True, default=None)),
                ('age_weeks', models.IntegerField(blank=True, default=None)),
                ('age_days', models.IntegerField(blank=True, default=None)),
                ('dob_estimate', models.DateTimeField(default=None)),
                ('location', models.CharField(blank=True, default='Shelter', max_length=255, null=True)),
                ('fee', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, default=None, null=True)),
                ('color', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, default=None, null=True)),
                ('name', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
        ),
    ]
