# Generated by Django 3.1.1 on 2021-03-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='species',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
