# Generated by Django 3.1.1 on 2021-03-15 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_auto_20210315_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='breed',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
