# Generated by Django 3.1.1 on 2021-03-15 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0004_auto_20210315_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='age_days',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='age_months',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='age_weeks',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='age_years',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
