# Generated by Django 3.1.1 on 2021-03-15 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0005_auto_20210315_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='dob_estimate',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
