# Generated by Django 3.1.1 on 2021-03-19 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0006_auto_20210315_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='dob_estimate',
        ),
        migrations.AddField(
            model_name='animal',
            name='intake_employee',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='intake_type',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='neutered_or_spayed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='animal',
            name='gender',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
