# Generated by Django 3.1.1 on 2021-03-20 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0007_auto_20210319_0314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='notes',
            new_name='medical_notes',
        ),
        migrations.AddField(
            model_name='animal',
            name='other_notes',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='shelter_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, unique=True),
        ),
    ]
