# Generated by Django 3.1.1 on 2021-03-21 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0008_auto_20210320_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='current_status',
            field=models.CharField(default='intake', max_length=255),
        ),
    ]
