# Generated by Django 3.1.1 on 2021-03-22 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0009_animal_current_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='age_days',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='age_months',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='age_weeks',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='age_years',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='fee',
        ),
        migrations.AddField(
            model_name='animal',
            name='age',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
