# Generated by Django 3.1.1 on 2021-03-23 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0012_animal_img_src'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='img_src',
        ),
    ]
